blueprint:
  custom_cards:
  - mushroom-light-card
  description: replaces light card with mushroom light card by Bourner
  name: Replace Mushroom Light Card
  type: replace-card
  version: '1.1'
card:
  entity: $replace_with_input_entity$
  name: $replace_with_input_name$
  hide_state: false
  show_brightness_control: true
  show_color_control: true
  show_color_temp_control: true
  type: custom:mushroom-light-card
  use_light_color: true
  collapsible_controls: true
  fill_container: false
