blueprint:
  custom_cards:
  - mushroom-update-card
  - auto-entities
  description: Update page by Bourner
  name: Update Page Blueprint
  type: page
  version: '1.0'
card:
  items_classes: col-xs-12 col-sm-6 col-md-3 col-lg-3
  type: custom:dwains-flexbox-card
filter:
  include:
    - domain: update
      options:
        show_buttons_control: true
        type: custom:mushroom-update-card
        use_entity_picture: true
sort:
  exclude: []
  method: state
  numeric: true
type: custom:auto-entities
