blueprint:
  name: Formula One Blueprint
  description: Formula One Blueprint by Michel Jourdain
  version: "4.0"

  type: page

  custom_cards:
    - button-card
    - formulaone-card
    - state-switch

  input:
    01_translate_last:
      name: Last in your language
      description: Translate Last Race in your language
      type: text-field

    02_translate_race:
      name: Race in your language
      description: Translate Race in your language
      type: text-field

    03_translate_next_race:
      name: Next race in your language
      description: Translate next race in your language
      type: text-field

    04_translate_last_result:
      name: Last result in your language
      description: Translate last result in your language
      type: text-field

    05_translate_date:
      name: Date in your language
      description: Translate date in your language
      type: text-field

    06_translate_practice:
      name: Practice in your language
      description: Translate practice in your language
      type: text-field

    07_translate_race_name:
      name: Race name in your language
      description: Translate Race name in your language
      type: text-field

    08_translate_circuit_name:
      name: Circuit name in your language
      description: Translate Circuit name in your language
      type: text-field

    09_translate_location:
      name: Location in your language
      description: Translate Location in your language
      type: text-field

    10_translate_city:
      name: City in your language
      description: Translate City in your language
      type: text-field

    11_translate_sprint:
      name: Sprint in your language
      description: Translate Sprint in your language
      type: text-field

    12_translate_qualifying:
      name: Qualifying in your language
      description: Translate Qualifying in your language
      type: text-field

    13_translate_stand:
      name: Stand in your language
      description: Translate stand in your language
      type: text-field

    14_translate_drivers_standings:
      name: Drivers standings in your language
      description: Translate drivers standings in your language
      type: text-field

    15_translate_constructors_standings:
      name: Constructors standings in your language
      description: Translate constructor standings in your language
      type: text-field

    16_translate_endofseason:
      name: End of season in your language
      description: Translate End of season in your language
      type: text-field

    17_translate_points:
      name: Points in your language
      description: Translate Points in your language
      type: text-field

    18_translate_driver:
      name: Driver in your language
      description: Translate Driver in your language
      type: text-field

    19_translate_grid:
      name: Grid in your language
      description: Translate Grid in your language
      type: text-field

    20_translate_status:
      name: Status in your language
      description: Translate Status in your language
      type: text-field

    21_translate_wins:
      name: Wins in your language
      description: Translate Wins in your language
      type: text-field

    22_translate_team:
      name: Team in your language
      description: Translate Team in your language
      type: text-field

    23_translate_schedule:
      name: Schedule in your language
      description: Translate Schedule in your language
      type: text-field

    24_translate_constructor:
      name: Constructor in your language
      description: Translate Constructor in your language
      type: text-field

    25_translate_time:
      name: Time in your language
      description: Translate Time in your language
      type: text-field

    26_translate_day_abbreviation:
      name: Day abbreviation in your language
      description: Translate Day abbreviation in your language Ex - d, j
      type: text-field

    27_translate_hour_abbreviation:
      name: Hour abbreviation in your language
      description: Translate Hour abbreviation in your language Ex - h,
      type: text-field

    28_translate_minute_abbreviation:
      name: Minute abbreviation in your language
      description: Translate minute abbreviation in your language Ex - m
      type: text-field

    29_translate_second_abbreviation:
      name: Seconde abbreviation in your language
      description: Translate second abbreviation in your language Ex - s
      type: text-field

    40_local_contry:
      name: Local contry
      description: Your contry for the race time. Ex, fr, ca, nl..
      type: text-field

card:
  type: custom:dwains-flexbox-card
  items_classes: col-xs-12
  cards:
    - type: vertical-stack
      item_classes: "col-xs-12 col-sm-5"
      cards:
        - type: markdown
          content: "![Image](https://upload.wikimedia.org/wikipedia/commons/thumb/3/33/F1.svg/1280px-F1.svg.png)"

        - type: custom:formulaone-card
          card_type: countdown
          translations:
            days: $26_translate_day_abbreviation$
            hours': $27_translate_hour_abbreviation$
            minutes': $28_translate_minute_abbreviation$
            seconds': $29_translate_second_abbreviation$

        - card_type: next_race
          date_locale: $40_local_contry$
          image_clickable: false
          sensor: sensor.formula_one_sensor_races
          title: $03_translate_next_race$
          translations:
            "date": "$05_translate_date$"
            "practice1": "$06_translate_practice$ 1"
            "practice2": "$06_translate_practice$ 2"
            "practice3": "$06_translate_practice$ 3"
            "race": "$02_translate_race$"
            "racename": "$07_translate_race_name$"
            "circuitname": "$08_translate_circuit_name$"
            "location": "$09_translate_location$"
            "city": "$10_translate_city$"
            "racetime": "$02_translate_race$"
            "sprint": "$11_translate_sprint$"
            "qualifying": "$12_translate_qualifying$"
            "endofseason": "$16_translate_endofseason$ !"
          type: custom:formulaone-card

    - type: vertical-stack
      item_classes: "col-xs-12 col-sm-7"
      cards:
        - type: custom:state-switch
          default: last_race
          entity: hash
          states:
            last_race:
              type: vertical-stack
              cards:
                - type: custom:dwains-flexbox-card
                  padding: true
                  cards:
                    - type: horizontal-stack
                      cards:
                        - name: $01_translate_last$
                          tap_action:
                            action: navigate
                            navigation_path: "#last_race"
                          type: custom:button-card
                          styles:
                            card:
                              - height: 30px
                              - width: 115px
                            name:
                              - color: lightblue
                              - font-weight: bold
                              - font-size: 16px
                        - name: $13_translate_stand$
                          tap_action:
                            action: navigate
                            navigation_path: "#stands"
                          type: custom:button-card
                          styles:
                            card:
                              - height: 30px
                              - width: 115px
                            name:
                              - font-size: 16px
                        - name: $23_translate_schedule$
                          tap_action:
                            action: navigate
                            navigation_path: "#kalender"
                          type: custom:button-card
                          styles:
                            card:
                              - height: 30px
                              - width: 115px
                            name:
                              - font-size: 16px
                - card_type: last_result
                  sensor: sensor.formula_one_sensor_last_result
                  title: $04_translate_last_result$
                  translations:
                    "points": "$17_translate_points$"
                    "driver": "$18_translate_driver$"
                    "grid": "$19_translate_grid$"
                    "status": "$20_translate_status$"
                  type: custom:formulaone-card

            stands:
              type: vertical-stack
              cards:
                - type: custom:dwains-flexbox-card
                  padding: true
                  cards:
                    - type: horizontal-stack
                      cards:
                        - name: $01_translate_last$
                          tap_action:
                            action: navigate
                            navigation_path: "#last_race"
                          type: custom:button-card
                          styles:
                            card:
                              - height: 30px
                              - width: 115px
                            name:
                              - font-size: 16px
                        - name: $13_translate_stand$
                          styles:
                            card:
                              - height: 30px
                              - width: 115px
                            name:
                              - color: lightblue
                              - font-weight: bold
                              - font-size: 16px
                          tap_action:
                            action: navigate
                            navigation_path: "#stands"
                          type: custom:button-card
                        - name: $23_translate_schedule$
                          tap_action:
                            action: navigate
                            navigation_path: "#kalender"
                          type: custom:button-card
                          styles:
                            card:
                              - height: 30px
                              - width: 115px
                            name:
                              - font-size: 16px
                - card_type: driver_standings
                  sensor: sensor.formula_one_sensor_drivers
                  title: $14_translate_drivers_standings$
                  standings:
                    show_flag: true
                    show_team: true
                  translations:
                    "points": "$17_translate_points$"
                    "wins": "$21_translate_wins$"
                    "team": "$22_translate_team$"
                    "driver": "$18_translate_driver$"
                  type: custom:formulaone-card
                - card_type: constructor_standings
                  sensor: sensor.formula_one_sensor_constructors
                  title: $15_translate_constructors_standings$
                  translations:
                    "constructor": "$24_translate_constructor$"
                    "points": "$17_translate_points$"
                    "wins": "$21_translate_wins$"
                  type: custom:formulaone-card

            kalender:
              type: vertical-stack
              cards:
                - type: custom:dwains-flexbox-card
                  padding: true
                  cards:
                    - type: horizontal-stack
                      cards:
                        - name: $01_translate_last$
                          tap_action:
                            action: navigate
                            navigation_path: "#last_race"
                          type: custom:button-card
                          styles:
                            card:
                              - height: 30px
                              - width: 115px
                            name:
                              - font-size: 16px
                        - name: $13_translate_stand$
                          tap_action:
                            action: navigate
                            navigation_path: "#stands"
                          type: custom:button-card
                          styles:
                            card:
                              - height: 30px
                              - width: 115px
                            name:
                              - font-size: 16px
                        - name: $23_translate_schedule$
                          styles:
                            card:
                              - height: 30px
                              - width: 115px
                            name:
                              - color: lightblue
                              - font-weight: bold
                              - font-size: 16px
                          tap_action:
                            action: navigate
                            navigation_path: "#kalender"
                          type: custom:button-card
                - card_type: schedule
                  date_locale: $40_local_contry$
                  sensor: sensor.formula_one_sensor_races
                  title: $23_translate_schedule$
                  translations:
                    "date": "$05_translate_date$"
                    "race": "$02_translate_race$"
                    "location": "$09_translate_location$"
                    "endofseason": "$16_translate_endofseason$ !"
                    "time": "$25_translate_time$"
                  type: custom:formulaone-card
