blueprint:
  name: Formula One Blueprint
  description: Formula One Blueprint by Michel Jourdain
  version: 5.1

  type: page

  custom_cards:
    - formulaone-card
    - tabbed-card

  input:

    02_translate_race:
      name: Race in your language
      description: Translate Race in your language
      type: text-field

    03_translate_next_race:
      name: Next race in your language
      description: Translate next race in your language
      type: text-field

    04_translate_last_result:
      name: Last result in your language
      description: Translate last result in your language
      type: text-field

    05_translate_date:
      name: Date in your language
      description: Translate date in your language
      type: text-field

    06_translate_practice:
      name: Practice in your language
      description: Translate practice in your language
      type: text-field

    07_translate_race_name:
      name: Race name in your language
      description: Translate Race name in your language
      type: text-field

    08_translate_circuit_name:
      name: Circuit name in your language
      description: Translate Circuit name in your language
      type: text-field

    09_translate_location:
      name: Location in your language
      description: Translate Location in your language
      type: text-field

    10_translate_city:
      name: City in your language
      description: Translate City in your language
      type: text-field

    11_translate_sprint:
      name: Sprint in your language
      description: Translate Sprint in your language
      type: text-field

    12_translate_qualifying:
      name: Qualifying in your language
      description: Translate Qualifying in your language
      type: text-field

    14_translate_drivers_standings:
      name: Drivers standings in your language
      description: Translate drivers standings in your language
      type: text-field

    15_translate_constructors_standings:
      name: Constructors standings in your language
      description: Translate constructor standings in your language
      type: text-field

    16_translate_endofseason:
      name: End of season in your language
      description: Translate End of season in your language
      type: text-field

    17_translate_points:
      name: Points in your language
      description: Translate Points in your language
      type: text-field

    18_translate_driver:
      name: Driver in your language
      description: Translate Driver in your language
      type: text-field

    19_translate_grid:
      name: Grid in your language
      description: Translate Grid in your language
      type: text-field

    20_translate_status:
      name: Status in your language
      description: Translate Status in your language
      type: text-field

    21_translate_wins:
      name: Wins in your language
      description: Translate Wins in your language
      type: text-field

    22_translate_team:
      name: Team in your language
      description: Translate Team in your language
      type: text-field

    23_translate_schedule:
      name: Schedule in your language
      description: Translate Schedule in your language
      type: text-field

    24_translate_constructor:
      name: Constructor in your language
      description: Translate Constructor in your language
      type: text-field

    25_translate_time:
      name: Time in your language
      description: Translate Time in your language
      type: text-field

    26_translate_day_abbreviation:
      name: Day abbreviation in your language
      description: Translate Day abbreviation in your language Ex - d, j
      type: text-field

    27_translate_hour_abbreviation:
      name: Hour abbreviation in your language
      description: Translate Hour abbreviation in your language Ex - h
      type: text-field

    28_translate_minute_abbreviation:
      name: Minute abbreviation in your language
      description: Translate minute abbreviation in your language Ex - m
      type: text-field

    29_translate_second_abbreviation:
      name: Seconde abbreviation in your language
      description: Translate second abbreviation in your language Ex - s
      type: text-field

    30_translate_season:
      name: Season in your language
      description: Translate Season in your language
      type: text-field

    31_translate_select_season:
      name: Select season in your language
      description: Translate Select season in your language
      type: text-field

    32_translate_select_race:
      name: Select race in your language
      description: Translate Select race in your language
      type: text-field

    33_translate_past_race:
      name: Please select a race thats already been run in your language
      description: Translate Please select a race thats already been run in your language
      type: text-field

    40_local_contry:
      name: Local contry
      description: Your contry for the race time. Ex, fr, ca, nl..
      type: text-field

card:

  type: custom:dwains-flexbox-card
  items_classes: col-xs-12
  cards:
  
    - type: vertical-stack
      item_classes: col-xs-12 col-sm-6
      cards:
      
        - type: markdown
          content: "![Image](https://upload.wikimedia.org/wikipedia/commons/thumb/3/33/F1.svg/1280px-F1.svg.png)"

        - type: custom:formulaone-card
          card_type: countdown
          show_raceinfo: true
          translations:
            days: $26_translate_day_abbreviation$
            hours': $27_translate_hour_abbreviation$
            minutes': $28_translate_minute_abbreviation$
            seconds': $29_translate_second_abbreviation$
            date: $05_translate_date$
            practice1: $06_translate_practice$ 1
            practice2: $06_translate_practice$ 2
            practice3: $06_translate_practice$ 3
            race: $02_translate_race$
            racename: $07_translate_race_name$
            circuitname: $08_translate_circuit_name$
            location: $09_translate_location$
            city: $10_translate_city$
            racetime: $02_translate_race$
            sprint: $11_translate_sprint$
            qualifying: $12_translate_qualifying$
            endofseason: $16_translate_endofseason$ 

    - type: vertical-stack
      item_classes: col-xs-12 col-sm-6
      cards:
      
        - type: custom:tabbed-card
          styles: # global styles applied to all tabs
            --mdc-theme-primary: lightblue
          options: {}
          tabs:
 
            - card:
                type: custom:formulaone-card
                card_type: results
                title: $04_translate_last_result$
                translations:
                  raceheader: $02_translate_race$
                  seasonheader: $30_translate_season$
                  selectseason: $31_translate_select_season$
                  selectrace: $32_translate_select_race$
                  noresults: $33_translate_past_race$
                  driver: $18_translate_driver$
                  grid: $19_translate_grid$
                  status: $20_translate_status$
                  point: $17_translate_points$
              attributes:
                icon: mdi:view-list

            - card:
                type: custom:formulaone-card
                card_type: schedule
                date_locale: $40_local_contry$
                title: $23_translate_schedule$
                translations:
                  date: $05_translate_date$
                  race: $02_translate_race$
                  location: $09_translate_location$
                  endofseason: $16_translate_endofseason$ !
                  time: $25_translate_time$
              attributes:
                icon: mdi:calendar-month
 
            - card:
                type: custom:formulaone-card
                title: $14_translate_drivers_standings$
                card_type: driver_standings
                standings:
                  show_flag: true
                  show_team: true
                  show_teamlogo: true
                translations:
                  points: $17_translate_points$
                  wins: $21_translate_wins$
                  team: $22_translate_team$
                  driver: $18_translate_driver$
              attributes:
                icon: mdi:account

            - card:
                type: custom:formulaone-card
                card_type: constructor_standings
                title: $15_translate_constructors_standings$
                standings:
                  show_teamlogo: true
                translations:
                  constructor: $24_translate_constructor$
                  points: $17_translate_points$
                  wins: $21_translate_wins$
              attributes:
                icon: mdi:microsoft-teams
                
