blueprint:
  custom_cards:
  - mushroom-person-card
  description: replaces person card with mushroom person card by Bourner
  name: Replace Mushroom Person Card
  type: replace-card
  version: '1.1'
card:
  entity: $replace_with_input_entity$
  name: $replace_with_input_name$
  use_entity_picture: true
  hide_state: false
  hide_name: false  
  type: custom:mushroom-person-card
