blueprint:
  custom_cards:
  - button-card
  - auto-entities
  description: Battery Page with colored Icons by Bourner
  name: Battery Page Color Blueprint
  type: page
  version: '1.0'
card:
  cards:
  - card:
      items_classes: col-xs-12 col-sm-6 col-md-3 col-lg-3
      padding: true
      type: custom:dwains-flexbox-card
    filter:
      include:
      - attributes:
          device_class: battery
        domain: sensor
        options:
          color: var(--primary-color)
          show_icon: true
          show_label: false
          show_last_changed: false
          show_name: true
          show_state: true
          state:
          - color: '#ff0000'
            icon: mdi:battery-outline
            operator: <=
            value: 0          
          - color: '#ff5b00'
            icon: mdi:battery-10
            operator: <=
            value: 10
          - color: '#ff8a00'
            icon: mdi:battery-20
            operator: <=
            value: 20
          - color: '#ffb300'
            icon: mdi:battery-30
            operator: <=
            value: 30
          - color: '#ffda00'
            icon: mdi:battery-40
            operator: <=
            value: 40
          - color: '#ffff00'
            icon: mdi:battery-50
            operator: <=
            value: 50
          - color: '#e3ff00'
            icon: mdi:battery-60
            operator: <=
            value: 60
          - color: '#c3ff00'
            icon: mdi:battery-70
            operator: <=
            value: 70
          - color: '#9eff00'
            icon: mdi:battery-80
            operator: <=
            value: 80
          - color: '#6fff00'
            icon: mdi:battery-90
            operator: <=
            value: 90
          - color: '#00ff00'
            icon: mdi:battery
            operator: <=
            value: 100
          styles:
            card:
            - border-radius: 12px
            - margin-bottom: 0px
            - padding-top: 14px
            - padding-bottom: 14px
            grid:
            - grid-template-areas: '"i s""i n"'
            - grid-template-columns: 30% 70%
            - grid-template-rows: min-content
            icon:
            - width: 55%
            img_cell:
            - width: 45px
            - height: 45px
            - background: var(--secondary-background-color)
            - border-radius: 100%
            label:
            - justify-self: start
            - align-self: left
            - font-size: 12px
            - color: var(--disabled-text-color)
            name:
            - justify-self: start
            - align-self: left
            - font-size: 13px
            - color: var(--primary-text-color)
            state:
            - color: var(--disabled-text-color)
            - justify-self: start
            - font-size: 15px
            - align-self: center
          type: custom:button-card
    sort:
      exclude: []
      method: state
      numeric: true
    type: custom:auto-entities
  - card:
      items_classes: col-xs-12 col-sm-6 col-md-3 col-lg-3
      padding: true
      type: custom:dwains-flexbox-card
    filter:
      include:
      - attributes:
          device_class: battery
        domain: binary_sensor
        options:
          color: var(--primary-color)
          show_icon: true
          show_label: false
          show_last_changed: false
          show_name: true
          show_state: true
          state:
          - color: '#ff0000'
            icon: mdi:battery-outline
            operator: <=
            value: 0          
          - color: '#ff5b00'
            icon: mdi:battery-10
            operator: <=
            value: 10
          - color: '#ff8a00'
            icon: mdi:battery-20
            operator: <=
            value: 20
          - color: '#ffb300'
            icon: mdi:battery-30
            operator: <=
            value: 30
          - color: '#ffda00'
            icon: mdi:battery-40
            operator: <=
            value: 40
          - color: '#ffff00'
            icon: mdi:battery-50
            operator: <=
            value: 50
          - color: '#e3ff00'
            icon: mdi:battery-60
            operator: <=
            value: 60
          - color: '#c3ff00'
            icon: mdi:battery-70
            operator: <=
            value: 70
          - color: '#9eff00'
            icon: mdi:battery-80
            operator: <=
            value: 80
          - color: '#6fff00'
            icon: mdi:battery-90
            operator: <=
            value: 90
          - color: '#00ff00'
            icon: mdi:battery
            operator: <=
            value: 100
          styles:
            card:
            - border-radius: 12px
            - margin-bottom: 0px
            - padding-top: 14px
            - padding-bottom: 14px
            grid:
            - grid-template-areas: '"i s""i n"'
            - grid-template-columns: 30% 70%
            - grid-template-rows: min-content
            icon:
            - width: 55%
            img_cell:
            - width: 45px
            - height: 45px
            - background: var(--secondary-background-color)
            - border-radius: 100%
            label:
            - justify-self: start
            - align-self: left
            - font-size: 12px
            - color: var(--disabled-text-color)
            name:
            - justify-self: start
            - align-self: left
            - font-size: 13px
            - color: var(--primary-text-color)
            state:
            - color: var(--disabled-text-color)
            - justify-self: start
            - font-size: 15px
            - align-self: center
          type: custom:button-card
    sort:
      exclude: []
      method: state
      numeric: true
    type: custom:auto-entities
  type: vertical-stack
