blueprint:
  custom_cards:
  - button-card
  description: Mercedes card by Bourner
  name: Mercedes Card Blueprint
  input:
    license:
      name: license plate
      description: type in your license plate with underscores
      type: text-field
  type: card
  version: '1.0'
card:
  cards:
  - name: Mercedes
    styles:
      card:
      - text-transform: uppercase
      - color: var(--dwains-theme-accent)
      - font-size: 125%
      - border-radius: 0%
      - font-weight: 100
      - letter-spacing: 10px
    type: custom:button-card
  - cards:
    - elements:
      - entity: sensor.$license$_fuel_level
        prefix: ''
        style:
          color: lightgrey
          left: 15%
          top: 17%
          transform: translate(-50%, -50%) scale(1.9, 1.9)
        type: state-label
      - entity: sensor.$license$_range_liquid
        prefix: ''
        style:
          color: lightgrey
          left: 17%
          top: 6%
          transform: translate(-50%, -50%) scale(0.7, 0.7)
        type: state-label
      - entity: sensor.$license$_odometer
        prefix: ' '
        style:
          color: lightgrey
          left: 39%
          top: 17%
          transform: translate(-50%, -50%) scale(1.3, 1.3)
        type: state-label
      - entity: sensor.$license$_service_days
        prefix: ' '
        style:
          color: lightgrey
          left: 49%
          top: 6%
          transform: translate(-50%, -50%) scale(0.7, 0.7)
        type: state-label
      - entity: sensor.$license$_window_sunroof
        style:
          --paper-item-icon-color: null
          left: 57%
          top: 8%
          transform: translate(-50%, -50%) scale(1.0, 1.0)
        type: state-icon
      - entity: binary_sensor.$license$_tire_warning
        prefix: ''
        style:
          color: '#FFFFFF'
          left: 66.5%
          top: 8%
          transform: translate(-50%, -50%) scale(1.0, 1.0)
        type: state-icon
      - entity: binary_sensor.$license$_low_brake_fluid_warning
        prefix: ''
        style:
          color: '#FFFFFF'
          left: 76%
          top: 8%
          transform: translate(-50%, -50%) scale(1.0, 1.0)
        type: state-icon
      - entity: binary_sensor.$license$_low_coolant_level_warning
        prefix: ''
        style:
          color: '#FFFFFF'
          left: 85.5%
          top: 8%
          transform: translate(-50%, -50%) scale(1.0, 1.0)
        type: state-icon
      - entity: binary_sensor.$license$_low_wash_water_warning
        prefix: ''
        style:
          color: '#FFFFFF'
          left: 95%
          top: 8%
          transform: translate(-50%, -50%) scale(1.0, 1.0)
        type: state-icon
      - entity: sensor.$license$_tire_pressure_front_right
        style:
          color: lightgrey
          left: 38%
          top: 32%
          transform: translate(-50%, -50%) scale(1.1, 1.1)
        type: state-label
      - entity: sensor.$license$_tire_pressure_rear_right
        style:
          color: lightgrey
          left: 84%
          top: 32%
          transform: translate(-50%, -50%) scale(1.1, 1.1)
        type: state-label
      - entity: sensor.$license$_tire_pressure_front_left
        style:
          color: lightgrey
          left: 38%
          top: 90%
          transform: translate(-50%, -50%) scale(1.1, 1.1)
        type: state-label
      - entity: sensor.$license$_tire_pressure_rear_left
        style:
          color: lightgrey
          left: 84%
          top: 90%
          transform: translate(-50%, -50%) scale(1.1, 1.1)
        type: state-label
      - entity: sensor.$license$_lock_front_right
        style:
          --paper-item-icon-color: white
          left: 61%
          top: 38%
          transform: translate(-50%, -50%) scale(1.1, 1.1)
        type: state-icon
      - entity: sensor.$license$_lock_rear_right
        style:
          --paper-item-icon-color: white
          left: 68%
          top: 38%
          transform: translate(-50%, -50%) scale(1.1, 1.1)
        type: state-icon
      - entity: sensor.$license$_lock_front_left
        style:
          --paper-item-icon-color: white
          left: 61%
          top: 83%
          transform: translate(-50%, -50%) scale(1.1, 1.1)
        type: state-icon
      - entity: sensor.$license$_lock_rear_left
        style:
          --paper-item-icon-color: white
          left: 68%
          top: 83%
          transform: translate(-50%, -50%) scale(1.1, 1.1)
        type: state-icon
      - entity: sensor.$license$_lock_trunk
        style:
          --paper-item-icon-color: white
          left: 95%
          top: 60%
          transform: translate(-50%, -50%) scale(1.1, 1.1)
        type: state-icon
      - entity: sensor.$license$_window_front_right
        style:
          --paper-item-icon-color: lightgrey
          left: 56%
          top: 31%
          transform: translate(-50%, -50%) scale(1.1, 1.1)
        type: state-icon
      - entity: sensor.$license$_window_rear_right
        style:
          --paper-item-icon-color: lightgrey
          left: 73%
          top: 31%
          transform: translate(-50%, -50%) scale(1.1, 1.1)
        type: state-icon
      - entity: sensor.$license$_window_front_left
        style:
          --paper-item-icon-color: lightgrey
          left: 56%
          top: 90%
          transform: translate(-50%, -50%) scale(1.1, 1.1)
        type: state-icon
      - entity: sensor.$license$_window_rear_left
        style:
          --paper-item-icon-color: lightgrey
          left: 73%
          top: 90%
          transform: translate(-50%, -50%) scale(1.0, 1.0)
        type: state-icon
      - entity: binary_sensor.$license$_park_brake_status
        prefix: ''
        style:
          color: '#FFFFFF'
          left: 57%
          top: 18.5%
          transform: translate(-50%, -50%) scale(1.0, 1.0)
        type: state-icon
      - entity: binary_sensor.$license$_windows_closed
        prefix: ''
        style:
          color: '#FFFFFF'
          left: 66%
          top: 18.5%
          transform: translate(-50%, -50%) scale(1.0, 1.0)
        type: state-icon
      - entity: sensor.$license$_lock_status
        prefix: ''
        style:
          color: lightgrey
          left: 19%
          top: 90%
          transform: translate(-50%, -50%) scale(0.7, 0.7)
        type: state-label
      - entity: device_tracker.$license$_device_tracker
        prefix: ''
        style:
          color: lightgrey
          left: 75.6%
          top: 19%
          transform: translate(-50%, -50%) scale(1.0, 1.0)
        type: state-label
      image: /local/merc2.png
      type: picture-elements
    type: vertical-stack
  - entities:
    - entity: binary_sensor.wash_car
      icon: fapro:car-wash-duotone
      name: Wash the car?
      secondary_info: last-updated
    state_color: true
    type: entities
  type: vertical-stack
