blueprint:
  name: Toggle card Blueprint
  type: card
  description: Toggle card by mase
  version: '1.0'
  custom_cards:
    - button-card
  input:
    toggle_entity:
      description: Entity to toggle
      name: Select entity
      type: entity-picker
    entity_name:
      description: This is the entity name
      name: Entity name
      type: text-field
    on_icon:
      description: This is the ON icon
      name: ON icon
      type: icon-picker
    off_icon:
      description: This is the OFF icon
      name: OFF icon
      type: icon-picker
card:
  entity: $toggle_entity$
  name: $entity_name$
  type: custom:button-card
  show_name: true
  show_icon: true
  show_state: true
  show_label: false
  show_last_changed: false
  tap_action:
    haptic: light
    action: toggle
  state:
    - value: 'on'
      icon: $on_icon$
    - value: 'off'
      icon: $on_icon$
      styles:
        icon: 
          - color: '#6c6c75'
  styles:
    grid:
      - grid-template-areas: '"i n""i s"'
      - grid-template-columns: 30% 70%
      - grid-template-rows: min-content
    card:
      - border-radius: 12px
      - margin-bottom: 0px
      - padding-top: 14px
      - padding-bottom: 14px
    icon:
      - width: 55%
      - color: var(--primary-color)
    img_cell:
      - width: 45px
      - height: 45px
      - border-radius: 100%
      - background: var(--secondary-background-color)
    name:
      - color: var(--primary-text-color)
      - justify-self: start
      - font-size: 15px
      - align-self: center
    state:
      - justify-self: start
      - align-self: left
      - font-size: 13px
      - color: var(--disabled-text-color)
    label:
      - justify-self: start
      - align-self: left
      - font-size: 12px
      - color: var(--disabled-text-color)
