blueprint:
  custom_cards:
  - button-card
  - auto-entities
  - scheduler-card
  - search-card
  description: Automation Page by Bourner
  name: Automation Page Blueprint
  type: page
  version: 1.1.0
card:
  cards:
  - type: custom:search-card
  - card:
      items_classes: col-xs-12 col-sm-6 col-md-2 col-lg-2
      padding: true
      type: custom:dwains-flexbox-card
    filter:
      include:
      - domain: automation
        options:
          color: var(--primary-color)
          show_icon: true
          show_label: false
          show_last_changed: false
          show_name: true
          show_state: true
          state:
          - icon: mdi:toggle-switch
            value: 'on'
          - icon: mdi:toggle-switch-outline
            styles:
              icon:
              - color: '#6c6c75'
            value: 'off'
          styles:
            card:
            - border-radius: 12px
            - margin-bottom: 0px
            - padding-top: 14px
            - padding-bottom: 14px
            grid:
            - grid-template-areas: '"i n""i s"'
            - grid-template-columns: 30% 70%
            - grid-template-rows: min-content
            icon:
            - width: 55%
            - color: var(--primary-color)
            img_cell:
            - width: 45px
            - height: 45px
            - border-radius: 100%
            - background: var(--secondary-background-color)
            label:
            - justify-self: start
            - align-self: left
            - font-size: 12px
            - color: var(--disabled-text-color)
            name:
            - color: var(--primary-text-color)
            - justify-self: start
            - font-size: 15px
            - align-self: center
            state:
            - justify-self: start
            - align-self: left
            - font-size: 13px
            - color: var(--disabled-text-color)
          type: custom:button-card
    sort:
      exclude: []
      ignore_case: true
      method: name
    type: custom:auto-entities
  - exclude: []
    include:
    - alarm_control_panel
    - automation
    - climate
    - group
    - light
    - lock
    - media_player
    - scene
    - script
    - switch
    - vacuum
    type: custom:scheduler-card
  type: vertical-stack
