blueprint:
  name: PersonsPopUpBlueprint
  description: Person Pop-Up bleuprint by Michel Jourdain
  version: "1.4"
  type: card
  
  custom_cards:
    - mini-graph-card
    - button-card
    - mushroom-person-card
    
  input:
  
    11_person_name:
      name: Name person one
      description: Name of the person one
      type: text-field
    12_person_entity:
      name: Person one entity
      description: Person one entity
      type: entity-picker
    13_tracker_entity:
      name: Tracker entity person one
      description: Tracker entity of person one
      type: entity-picker
    14_battery_charging_entity:
      name: Battery charging person one
      description: Battery charging entity of person one
      type: entity-picker
    15_battery_level_entity:
      name: Battery level person one
      description: Battery level entity of person one
      type: entity-picker
      
    50_translate_displacements_last_24_hours:
      name: Translate displacements last 24 hours
      description: Translate displacements last 24 hours in your language
      type: text-field 
    51_translate_battery_charge_level:
      name: Translate Battery charge level
      description: Translate Battery charge level in your language
      type: text-field  
    52_translate_battery_charging:
      name: Translate Battery charging
      description: Translate Battery charging in your language
      type: text-field    
    53_translate_map:
      name: Translate Map
      description: Translate Map in your language
      type: text-field    
 
    60_dark_mode:
       name: Dark mode map
       description: Dark mode for map
       type: checkbox
       default_value: false

card:

# Persons

  type: custom:dwains-flexbox-card
  items_classes: 'col-xs-12'
  cards:
    - type: vertical-stack
      cards:         
         
        - type: custom:mushroom-person-card
          entity: $12_person_entity$
          name: $11_person_name$
          icon: mdi:account-plus
          hide_name: false
          use_entity_picture: true
          hide_state: false

        - type: custom:dwains-heading-card
          title: $50_translate_displacements_last_24_hours$
                    
        - type: history-graph
          entities:
            - entity: $13_tracker_entity$
          hours_to_show: 24
          refresh_interval: 0
                    
        - type: custom:dwains-heading-card
          title: $52_translate_battery_charging$

        - type: history-graph
          entities:
            - entity: $14_battery_charging_entity$
          hours_to_show: 24
          refresh_interval: 0
                    
        - type: custom:dwains-heading-card
          title: $51_translate_battery_charge_level$
          
        - type: 'custom:mini-graph-card'
          entities: 
            - entity: $15_battery_level_entity$
          line_color: green
          hours_to_show: 24
          line_width: 2
          hour24: true
          points_per_hour: 2
          decimals: 0
          show:
            animate: true
            fill: true
            icon: false
            labels: false
            legend: false
            name: false
            graph: bar
            extrema: false
            average: false   
                          
        - type: custom:dwains-heading-card
          title: $53_translate_map$
        
        - type: map
          entities:
            - entity: $13_tracker_entity$
          aspect_ratio: 50%
          dark_mode: $60_dark_mode$
          hours_to_show: 24
          default_zoom: 12