blueprint:
  custom_cards:
  - mushroom-vacuum-card
  description: replaces vaccum card with mushroom vacuum card by Bourner
  name: Replace Mushroom Vacuum Card
  type: replace-card
  version: '1.1'
card:
  type: custom:mushroom-vacuum-card
  entity: $replace_with_input_entity$
  name: $replace_with_input_name$
  name: $name$
  hide_state: false
  commands:
    - start_pause
    - stop
    - locate
    - return_home
    - clean_spot
