blueprint:
  custom_cards:
  - mushroom-entity-card
  description: replaces entity card with mushroom entity card by Bourner
  name: Replace Mushroom Entity Card
  type: replace-card
  version: '1.1'
card:
  entity: $replace_with_input_entity$
  name: $replace_with_input_name$
  type: custom:mushroom-entity-card

  
