blueprint:
  name: ISS page Blueprint
  description: International Space Station page by Michel Jourdain
  version: "1.0"
  type: page
  
  custom_cards:
    - vertical-stack-in-card

  input:
  
    01_translate_number_of_peoples:
       name: Translate Number of people on board
       description: Translate Number of people on board in your language
       type: text-field
       
    02_translate_next_rise:
       name: Translate next rise
       description: Translate next rise in your language
       type: text-field
       
    03_translate_over_your_house:
       name: Translate over your house
       description: Translate over your house in your language
       type: text-field
       
    04_translate_longitude:
       name: Translate longitude
       description: Translate longitude in your language
       type: text-field
       
    05_translate_latitude:
       name: Translate latitude
       description: Translate latitude in your language
       type: text-field
       
    06_translate_informations:
       name: Translate informations
       description: Translate Informations in your language
       type: text-field
       
    07_disable_dark_mode:
       name: Disable dark mode
       description: Disable dark mode for map
       type: checkbox

card:

  type: custom:dwains-flexbox-card
  items_classes: 'col-xs-12'
  cards:

     - type: custom:vertical-stack-in-card
       item_classes: 'col-xs-12 col-sm-5'
       cards:
  
         - type: entities
           title: $06_translate_informations$
           entities:
             - entity: sensor.international_space_station_peoples_in
               name: $01_translate_number_of_peoples$
             - entity: sensor.international_space_station_next_rise
               name: $02_translate_next_rise$
             - entity: sensor.international_space_station_longitude
               name: $04_translate_longitude$
             - entity: sensor.international_space_station_latitude
               name: $05_translate_latitude$
           header:
             type: picture
             image: >-
                https://upload.wikimedia.org/wikipedia/commons/f/f2/Space_station_freedom_%281%29.jpg
           tap_action:
             action: none
           hold_action:
             action: none
                
         - type: history-graph
           entities:
             - entity: binary_sensor.iss
           title: ISS $03_translate_over_your_house$
           hours_to_show: 24

     - type: map
       item_classes: 'col-xs-12 col-sm-7'
       entities:
          - entity: binary_sensor.iss
       dark_mode: $07_disable_dark_mode$
       aspect_ratio: 92%
       hours_to_show: 2
       default_zoom: 1.5
