blueprint:
  name: FivePersonsBlueprint
  description: Five persons bleuprint by Michel Jourdain
  version: "2.0"
  type: page
  
  custom_cards:
    - tabbed-card
    - mini-graph-card
    - mushroom-person-card
    
  input:
  
    11_person_name:
      name: Name person one
      description: Name of the person one
      type: text-field
    12_person_entity:
      name: Person one entity
      description: Person one entity
      type: entity-picker
    13_tracker_entity:
      name: Tracker entity person one
      description: Tracker entity of person one
      type: entity-picker
    14_battery_charging_entity:
      name: Battery charging person one
      description: Battery charging entity of person one
      type: entity-picker
    15_battery_level_entity:
      name: Battery level person one
      description: Battery level entity person one
      type: entity-picker
      
    21_person_name:
      name: Name person two
      description: Name of the person two
      type: text-field
    22_person_entity:
      name: Person two entity
      description: Person two entity
      type: entity-picker
    23_tracker_entity:
      name: Tracker entity person two
      description: Tracker entity of person two
      type: entity-picker
    24_battery_charging_entity:
      name: Battery charging person two
      description: Battery charging entity of person two
      type: entity-picker
    25_battery_level_entity:
      name: Battery level person two
      description: Battery level entity of person two
      type: entity-picker
      
    31_person_name:
      name: Name person three
      description: Name of the person three
      type: text-field
    32_person_entity:
      name: Person three entity
      description: Person three entity
      type: entity-picker
    33_tracker_entity:
      name: Tracker entity person three
      description: Tracker entity of person three
      type: entity-picker
    34_battery_charging_entity:
      name: Battery charging person three
      description: Battery charging entity of person three
      type: entity-picker
    35_battery_level_entity:
      name: Battery level person three
      description: Battery level entity of person three
      type: entity-picker
      
    41_person_name:
      name: Name person four
      description: Name of the person four
      type: text-field
    42_person_entity:
      name: Person four entity
      description: Person four entity
      type: entity-picker
    43_tracker_entity:
      name: Tracker entity person four
      description: Tracker entity of person four
      type: entity-picker
    44_battery_charging_entity:
      name: Battery charging person four
      description: Battery charging entity of person four
      type: entity-picker
    45_battery_level_entity:
      name: Battery level person four
      description: Battery level entity of person four
      type: entity-picker
      
    51_person_name:
      name: Name person five
      description: Name of the person five
      type: text-field
    52_person_entity:
      name: Person five entity
      description: Person five entity
      type: entity-picker
    53_tracker_entity:
      name: Tracker entity person five
      description: Tracker entity of person five
      type: entity-picker
    54_battery_charging_entity:
      name: Battery charging person five
      description: Battery charging entity of person five
      type: entity-picker
    55_battery_level_entity:
      name: Battery level person five
      description: Battery level entity of person five
      type: entity-picker
      
    60_translate_displacements_last_24_hours:
      name: Translate displacements last 24 hours
      description: Translate displacements last 24 hours in your language
      type: text-field 
    61_translate_battery_charge_level:
      name: Translate Battery charge level
      description: Translate Battery charge level in your language
      type: text-field  
    62_translate_battery_charging:
      name: Translate Battery charging
      description: Translate Battery charging in your language
      type: text-field    
    63_translate_map:
      name: Translate Map
      description: Translate Map in your language
      type: text-field    
 
    70_dark_mode:
       name: Dark mode map
       description: Dark mode for map
       type: checkbox
       default_value: false

card:

  type: custom:tabbed-card
  attributes:
    isFadingIndicator: false
    minWidth: true
    isMinWidthIndicator: true
    stacked: false
  styles:
    --mdc-theme-primary: orange
    --mdc-tab-text-label-color-default: lightblue
  options: {}
  tabs:

    - card:
            
         type: custom:dwains-flexbox-card
         items_classes: col-xs-12
         cards:

               - type: vertical-stack
                 item_classes: col-xs-12 col-sm-7
                 cards:            
            
                  - type: custom:mushroom-person-card
                    entity: $12_person_entity$
                    name: $11_person_name$
                    icon: mdi:account-plus
                    hide_name: false
                    use_entity_picture: true
                    hide_state: false

                  - type: custom:dwains-heading-card
                    title: $60_translate_displacements_last_24_hours$
                    
                  - type: history-graph
                    entities:
                      - entity: $13_tracker_entity$
                        name: ' '
                    hours_to_show: 24
                    refresh_interval: 0
                    
                  - type: custom:dwains-heading-card
                    title: $62_translate_battery_charging$

                  - type: history-graph
                    entities:
                      - entity: $14_battery_charging_entity$
                        name: ' '
                    hours_to_show: 24
                    refresh_interval: 0
                    
                  - type: custom:dwains-heading-card
                    title: $61_translate_battery_charge_level$
          
                  - type: 'custom:mini-graph-card'
                    entities: 
                      - entity: $15_battery_level_entity$
                    line_color: green
                    hours_to_show: 24
                    line_width: 2
                    hour24: true
                    points_per_hour: 2
                    decimals: 0
                    show:
                      animate: true
                      fill: true
                      icon: false
                      labels: false
                      legend: false
                      name: false
                      graph: bar
                      extrema: false
                      average: false
                      
               - type: vertical-stack
                 item_classes: col-xs-12 col-sm-5
                 cards:     
                 
                  - type: custom:dwains-heading-card
                    title: $63_translate_map$
        
                  - type: map
                    entities:
                      - entity: $13_tracker_entity$
                    hours_to_show: 24
                    dark_mode: $70_dark_mode$
                    default_zoom: 12
      attributes:
          label: $11_person_name$
          icon: mdi:card-account-details
          
    - card:
            
         type: custom:dwains-flexbox-card
         items_classes: col-xs-12
         cards:

               - type: vertical-stack
                 item_classes: col-xs-12 col-sm-7
                 cards:            
            
                  - type: custom:mushroom-person-card
                    entity: $22_person_entity$
                    name: $21_person_name$
                    icon: mdi:account-plus
                    hide_name: false
                    use_entity_picture: true
                    hide_state: false

                  - type: custom:dwains-heading-card
                    title: $60_translate_displacements_last_24_hours$
                    
                  - type: history-graph
                    entities:
                      - entity: $23_tracker_entity$
                        name: ' '
                    hours_to_show: 24
                    refresh_interval: 0
                    
                  - type: custom:dwains-heading-card
                    title: $62_translate_battery_charging$

                  - type: history-graph
                    entities:
                      - entity: $24_battery_charging_entity$
                        name: ' '
                    hours_to_show: 24
                    refresh_interval: 0
                    
                  - type: custom:dwains-heading-card
                    title: $61_translate_battery_charge_level$
          
                  - type: 'custom:mini-graph-card'
                    entities: 
                      - entity: $25_battery_level_entity$
                    line_color: green
                    hours_to_show: 24
                    line_width: 2
                    hour24: true
                    points_per_hour: 2
                    decimals: 0
                    show:
                      animate: true
                      fill: true
                      icon: false
                      labels: false
                      legend: false
                      name: false
                      graph: bar
                      extrema: false
                      average: false
                      
               - type: vertical-stack
                 item_classes: col-xs-12 col-sm-5
                 cards:     
                 
                  - type: custom:dwains-heading-card
                    title: $63_translate_map$
        
                  - type: map
                    entities:
                      - entity: $23_tracker_entity$
                    hours_to_show: 24
                    dark_mode: $70_dark_mode$
                    default_zoom: 12
      attributes:
          label: $21_person_name$
          icon: mdi:card-account-details
          
    - card:
            
         type: custom:dwains-flexbox-card
         items_classes: col-xs-12
         cards:

               - type: vertical-stack
                 item_classes: col-xs-12 col-sm-7
                 cards:            
            
                  - type: custom:mushroom-person-card
                    entity: $32_person_entity$
                    name: $31_person_name$
                    icon: mdi:account-plus
                    hide_name: false
                    use_entity_picture: true
                    hide_state: false

                  - type: custom:dwains-heading-card
                    title: $60_translate_displacements_last_24_hours$
                    
                  - type: history-graph
                    entities:
                      - entity: $33_tracker_entity$
                        name: ' '
                    hours_to_show: 24
                    refresh_interval: 0
                    
                  - type: custom:dwains-heading-card
                    title: $62_translate_battery_charging$

                  - type: history-graph
                    entities:
                      - entity: $34_battery_charging_entity$
                        name: ' '
                    hours_to_show: 24
                    refresh_interval: 0
                    
                  - type: custom:dwains-heading-card
                    title: $61_translate_battery_charge_level$
          
                  - type: 'custom:mini-graph-card'
                    entities: 
                      - entity: $35_battery_level_entity$
                    line_color: green
                    hours_to_show: 24
                    line_width: 2
                    hour24: true
                    points_per_hour: 2
                    decimals: 0
                    show:
                      animate: true
                      fill: true
                      icon: false
                      labels: false
                      legend: false
                      name: false
                      graph: bar
                      extrema: false
                      average: false
                      
               - type: vertical-stack
                 item_classes: col-xs-12 col-sm-5
                 cards:     
                 
                  - type: custom:dwains-heading-card
                    title: $63_translate_map$
        
                  - type: map
                    entities:
                      - entity: $33_tracker_entity$
                    hours_to_show: 24
                    dark_mode: $70_dark_mode$
                    default_zoom: 12
      attributes:
          label: $31_person_name$
          icon: mdi:card-account-details
          
    - card:
            
         type: custom:dwains-flexbox-card
         items_classes: col-xs-12
         cards:

               - type: vertical-stack
                 item_classes: col-xs-12 col-sm-7
                 cards:            
            
                  - type: custom:mushroom-person-card
                    entity: $42_person_entity$
                    name: $41_person_name$
                    icon: mdi:account-plus
                    hide_name: false
                    use_entity_picture: true
                    hide_state: false

                  - type: custom:dwains-heading-card
                    title: $60_translate_displacements_last_24_hours$
                    
                  - type: history-graph
                    entities:
                      - entity: $43_tracker_entity$
                        name: ' '
                    hours_to_show: 24
                    refresh_interval: 0
                    
                  - type: custom:dwains-heading-card
                    title: $62_translate_battery_charging$

                  - type: history-graph
                    entities:
                      - entity: $44_battery_charging_entity$
                        name: ' '
                    hours_to_show: 24
                    refresh_interval: 0
                    
                  - type: custom:dwains-heading-card
                    title: $61_translate_battery_charge_level$
          
                  - type: 'custom:mini-graph-card'
                    entities: 
                      - entity: $45_battery_level_entity$
                    line_color: green
                    hours_to_show: 24
                    line_width: 2
                    hour24: true
                    points_per_hour: 2
                    decimals: 0
                    show:
                      animate: true
                      fill: true
                      icon: false
                      labels: false
                      legend: false
                      name: false
                      graph: bar
                      extrema: false
                      average: false
                      
               - type: vertical-stack
                 item_classes: col-xs-12 col-sm-5
                 cards:     
                 
                  - type: custom:dwains-heading-card
                    title: $63_translate_map$
        
                  - type: map
                    entities:
                      - entity: $43_tracker_entity$
                    hours_to_show: 24
                    dark_mode: $70_dark_mode$
                    default_zoom: 12
      attributes:
          label: $41_person_name$
          icon: mdi:card-account-details
          
    - card:
            
         type: custom:dwains-flexbox-card
         items_classes: col-xs-12
         cards:

               - type: vertical-stack
                 item_classes: col-xs-12 col-sm-7
                 cards:            
            
                  - type: custom:mushroom-person-card
                    entity: $52_person_entity$
                    name: $51_person_name$
                    icon: mdi:account-plus
                    hide_name: false
                    use_entity_picture: true
                    hide_state: false

                  - type: custom:dwains-heading-card
                    title: $60_translate_displacements_last_24_hours$
                    
                  - type: history-graph
                    entities:
                      - entity: $53_tracker_entity$
                        name: ' '
                    hours_to_show: 24
                    refresh_interval: 0
                    
                  - type: custom:dwains-heading-card
                    title: $62_translate_battery_charging$

                  - type: history-graph
                    entities:
                      - entity: $54_battery_charging_entity$
                        name: ' '
                    hours_to_show: 24
                    refresh_interval: 0
                    
                  - type: custom:dwains-heading-card
                    title: $61_translate_battery_charge_level$
          
                  - type: 'custom:mini-graph-card'
                    entities: 
                      - entity: $55_battery_level_entity$
                    line_color: green
                    hours_to_show: 24
                    line_width: 2
                    hour24: true
                    points_per_hour: 2
                    decimals: 0
                    show:
                      animate: true
                      fill: true
                      icon: false
                      labels: false
                      legend: false
                      name: false
                      graph: bar
                      extrema: false
                      average: false
                      
               - type: vertical-stack
                 item_classes: col-xs-12 col-sm-5
                 cards:     
                 
                  - type: custom:dwains-heading-card
                    title: $63_translate_map$
        
                  - type: map
                    entities:
                      - entity: $53_tracker_entity$
                    hours_to_show: 24
                    dark_mode: $70_dark_mode$
                    default_zoom: 12
      attributes:
          label: $51_person_name$
          icon: mdi:card-account-details
