blueprint:
  custom_cards:
  - mushroom-fan-card
  description: replaces fan card with mushroom fan card by Bourner
  input:
    name: null
  name: Replace Mushroom Fan Card
  type: card
  version: '1.0'
card:
  entity: $replace_with_input_entity$
  show_oscillate_control: true
  show_percentage_control: true
  icon_animation: true
  hide_state: false
  type: custom:mushroom-fan-card
