- platform: template
  sensors:      
    formula_1:
      friendly_name: Formula 1
      icon_template: mdi:keyboard-f1
      value_template: >
        {% set raceWeekNr = as_timestamp(strptime(state_attr('calendar.formula_1_calendar_fp1', 'start_time'), '%d %h %m')) | timestamp_custom('%U') %}
        {% set curWeekNr = as_timestamp(now()) | timestamp_custom('%U') %}
        
        {% if raceWeekNr != curWeekNr %}
          No race planned for this week.
        {% else %}
          There is a race planned for this week.
        {% endif %}
      attribute_templates:
        free_practice_1_day: >
            {{ as_timestamp(strptime(state_attr('calendar.formula_1_calendar_fp1', 'start_time'), '%d %h %m')) | timestamp_custom('%A %d %B') }}
        free_practice_1_time: >
            {{ as_timestamp(strptime(state_attr('calendar.formula_1_calendar_fp1', 'start_time'), '%d %h %m')) | timestamp_custom('%H:%M') }}
        free_practice_2_day: >
            {{ as_timestamp(strptime(state_attr('calendar.formula_1_calendar_fp2', 'start_time'), '%d %h %m')) | timestamp_custom('%A %d %B') }}
        free_practice_2_time: >
            {{ as_timestamp(strptime(state_attr('calendar.formula_1_calendar_fp2', 'start_time'), '%d %h %m')) | timestamp_custom('%H:%M') }}
        free_practice_3_day: >
            {{ as_timestamp(strptime(state_attr('calendar.formula_1_calendar_fp3', 'start_time'), '%d %h %m')) | timestamp_custom('%A %d %B') }}
        free_practice_3_time: >
            {{ as_timestamp(strptime(state_attr('calendar.formula_1_calendar_fp3', 'start_time'), '%d %h %m')) | timestamp_custom('%H:%M') }}
        qualifying_day: >
            {{ as_timestamp(strptime(state_attr('calendar.formula_1_calendar_qualifying', 'start_time'), '%d %h %m')) | timestamp_custom('%A %d %B') }}
        qualifying_time: >
            {{ as_timestamp(strptime(state_attr('calendar.formula_1_calendar_qualifying', 'start_time'), '%d %h %m')) | timestamp_custom('%H:%M') }}
        race_day: >
            {{ as_timestamp(strptime(state_attr('calendar.formula_1_calendar_race', 'start_time'), '%d %h %m')) | timestamp_custom('%A %d %B') }}
        race_time: >
            {{ as_timestamp(strptime(state_attr('calendar.formula_1_calendar_race', 'start_time'), '%d %h %m')) | timestamp_custom('%H:%M') }}
        race_track: >
            {{ state_attr('calendar.formula_1_calendar_race', 'location') }}
        race_name: >
            {{ state_attr('calendar.formula_1_calendar_race', 'message') | replace ('Race: 2021 ','') }}