#Formula 1 Dwains Dashboard Add-on (more_page)
# Creator: LRvdLinden
# Website: https://github.com/LRvdLinden
# Blueprint v1.0 is only for Dwains Dashboard > v3.0


blueprint:
  name: Formula One
  description: Formula One page by LRvdLinden
  version: "1.0"
  type: page
  custom_cards:
  - button-card

card:    
  type: custom:dwains-flexbox-card
  items_classes: "col-xs-12"
  cards:
    - type: vertical-stack
      item_classes: "col-xs-12 col-sm-5"
      cards:
        - type: markdown
          content: >
            ![Image](https://upload.wikimedia.org/wikipedia/commons/thumb/3/33/F1.svg/1280px-F1.svg.png)

        - type: markdown
          card_mod:
          style:
            ha-markdown$: |
              * {
                font-family: FormulaOne, "Titillium Web";
              }
          content: >-
            {% set f1 = states.sensor.formula_one_sensor.attributes.next_race %} {% if
            not(f1 == None) %}  <h1><img height="22"
            src="https://www.countries-ofthe-world.com/flags-normal/flag-of-{{f1.Circuit.Location.country.replace(" ", "-")}}.png">&nbsp;
            {{ f1.raceName }}</h1> {{f1.Circuit.circuitName}} {% endif %} | <small>{{ as_timestamp(f1.date + ' ' + f1.time) | timestamp_custom("Race start %d-%m-%Y om %H:%M uur") }}</small>&nbsp;&nbsp;

            <a target="_new" href="{{f1.Circuit.url}}">
              <img width="100%" src="https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/Circuit%20maps%2016x9/{{f1.Circuit.Location.country.replace(" ", "_")}}_Circuit.png.transform/9col/image.png">
            </a>

  #Match VIEWS
    - type: vertical-stack
      item_classes: "col-xs-12 col-sm-7"
      cards:
        - type: custom:state-switch
          entity: hash
          default: race
          states:
           #schedule VIEW
            race:
              type: vertical-stack
              cards:
                  # Header
                - type: custom:dwains-flexbox-card
                  padding: true
                  cards:
                    - type: horizontal-stack
                      cards:
                        - type: custom:button-card
                          name: Race 
                          styles:
                            card:
                              - height: 30px
                              - width: 125px
                            name:
                              - color: var(--dwains-theme-accent)
                              - font-weight: bold
                              - font-size: 16px
                          tap_action:
                            action: navigate
                            navigation_path: "#race"
                        - type: custom:button-card
                          name: Stands 
                          styles:
                            card:
                              - height: 30px
                              - width: 125px
                            name:
                              - color: var(--dwains-theme-grey)
                              - font-weight: bold
                              - font-size: 16px
                          tap_action:
                            action: navigate
                            navigation_path: "#stands"
                # Calendar
                - type: custom:atomic-calendar-revive
                  showProgressBar: true
                  maxDaysToShow: 30
                  maxEventCount: 5
                  europeanDate: true
                  showNoEventsForToday: true
                  showMonth: true
                  showWeekDay: true
                  hideFinishedEvents: true
                  entities:
                    - calendar.formula_1_calendar_by_racefans_net

          #STANDS VIEW
            stands:
              type: vertical-stack
              cards:
                - type: custom:dwains-flexbox-card
                  padding: true
                  cards:
                   # Header
                    - type: horizontal-stack
                      cards:
                        - type: custom:button-card
                          name: Race 
                          styles:
                            card:
                              - height: 30px
                              - width: 125px
                            name:
                              - color: var(--dwains-theme-grey)
                              - font-weight: bold
                              - font-size: 16px
                          tap_action:
                            action: navigate
                            navigation_path: "#race"
                        - type: custom:button-card
                          name: Stands 
                          styles:
                            card:
                              - height: 30px
                              - width: 125px
                            name:
                              - color: var(--dwains-theme-accent)
                              - font-weight: bold
                              - font-size: 16px
                          tap_action:
                            action: navigate
                            navigation_path: "#stands"
                # Drivers
                - type: markdown
                  card_mod:
                    style:
                      ha-markdown$: |
                        table {
                          width: 100%;
                          border-spacing: 0;
                          border-collapse: separate;
                        }
                        th {
                            color: white;
                            background: rgb(41, 158, 194);
                        }
                        tr:nth-child(even) {
                          background-color: var(--primary-background-color);
                          color: rgb(41, 158, 194);
                        }
                        td:nth-child(1) {
                          width: 50px;
                          text-align: center;
                        }
                        td:nth-child(2) {
                          width: 50px;
                          text-align: center;
                        }
                        td:nth-child(4) {
                          width: 60px;
                          text-align: center;
                        }
                  content: |-
                    <table>
                      <thead>
                        <tr>
                          <th>&nbsp;</th>
                          <th colspan="2">Drivers</th>
                          <th class="center">Pts</th>
                        </tr>
                      </thead>
                      <tbody>
                    {% for driver in states.sensor.formula_one_sensor.attributes.drivers %} <tr>
                            <td>{{driver.position}}</td>
                            <td>{{driver.Driver.code}}</td>
                            <td>{{driver.Driver.givenName }} {{driver.Driver.familyName }}</td>
                            <td>{{driver.points}}</td>
                        </tr>
                    {% endfor %}
                      </tbody>
                    </table>
                # Constructors
                - type: markdown
                  card_mod:
                    style:
                      ha-markdown$: |
                        table {
                          width: 100%;
                          border-spacing: 0;
                          border-collapse: separate;
                        }
                        th {
                            color: white;
                            background: rgb(41, 158, 194);
                        }
                        tr:nth-child(even) {
                          background-color: var(--primary-background-color);
                          color: rgb(41, 158, 194);
                        }
                        td:nth-child(1) {
                          width: 50px;
                          text-align: center;
                        }
                        td:nth-child(2) {
                          text-align: left;
                        }
                        td:nth-child(3) {
                          width: 60px;
                          text-align: center;
                        }
                  content: |-
                    <table>
                      <thead>
                        <tr>
                          <th>&nbsp;</th>
                          <th>Constructor</th>
                          <th class="center">Pts</th>
                        </tr>
                      </thead>
                      <tbody>
                    {% for driver in states.sensor.formula_one_sensor.attributes.constructors %} <tr>
                            <td>{{driver.position}}</td>
                            <td>{{driver.Constructor.name }}</td>
                            <td>{{driver.points}}</td>
                        </tr>
                    {% endfor %}
                      </tbody>
                    </table>
